#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for GreenshiftWP Integration
# Spec: 002-i-need-to-integrate-the-plugin-with-greenshiftwp-a

set -e

echo "========================================"
echo "FRS User Profiles - GreenshiftWP Integration"
echo "Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_DIR="/Users/cedarstone/Local Sites/tutorlms-exploration/app/public/wp-content/plugins/frs-wp-users"

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Verifying prerequisites..."

# Check PHP
if command -v php &> /dev/null; then
    echo -e "${GREEN}✓ PHP found:${NC} $(php -v | head -1)"
else
    echo -e "${RED}✗ PHP not found${NC}"
    exit 1
fi

# Check NPM
if command -v npm &> /dev/null; then
    echo -e "${GREEN}✓ NPM found:${NC} $(npm -v)"
else
    echo -e "${RED}✗ NPM not found${NC}"
    exit 1
fi

# Check Composer
if command -v composer &> /dev/null; then
    echo -e "${GREEN}✓ Composer found:${NC} $(composer --version | head -1)"
else
    echo -e "${YELLOW}⚠ Composer not found (optional for development)${NC}"
fi

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo "Verifying project structure..."

cd "$PROJECT_DIR"

# Check key directories exist
if [ -d "includes/Integrations" ]; then
    echo -e "${GREEN}✓ includes/Integrations directory exists${NC}"
else
    echo -e "${RED}✗ includes/Integrations directory missing${NC}"
    exit 1
fi

if [ -d "includes/Controllers" ]; then
    echo -e "${GREEN}✓ includes/Controllers directory exists${NC}"
else
    echo -e "${RED}✗ includes/Controllers directory missing${NC}"
    exit 1
fi

# Check pattern files exist
if [ -f "includes/Integrations/FluentCRMSync.php" ]; then
    echo -e "${GREEN}✓ FluentCRMSync.php pattern file exists${NC}"
else
    echo -e "${YELLOW}⚠ FluentCRMSync.php not found - will need alternate pattern${NC}"
fi

if [ -f "includes/Controllers/Shortcodes.php" ]; then
    echo -e "${GREEN}✓ Shortcodes.php pattern file exists${NC}"
else
    echo -e "${YELLOW}⚠ Shortcodes.php not found - will need alternate pattern${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if node_modules exists
if [ -d "node_modules" ]; then
    echo -e "${GREEN}✓ node_modules exists${NC}"
else
    echo "Installing npm dependencies..."
    npm install
fi

# Check if vendor exists
if [ -d "vendor" ]; then
    echo -e "${GREEN}✓ vendor directory exists${NC}"
else
    echo "Installing composer dependencies..."
    composer install
fi

# ============================================
# VERIFY AUTOLOADER
# ============================================

echo ""
echo "Verifying autoloader..."

php -r "
require_once 'vendor/autoload.php';
\$checks = [
    'FRSUsers\\Models\\Profile' => 'Profile model',
    'FRSUsers\\Traits\\Base' => 'Base trait',
    'FRSUsers\\Integrations\\FluentCRMSync' => 'FluentCRM pattern',
    'FRSUsers\\Controllers\\Shortcodes' => 'Shortcodes pattern',
];
foreach (\$checks as \$class => \$name) {
    if (class_exists(\$class) || trait_exists(\$class)) {
        echo \"✓ \$name loaded\\n\";
    } else {
        echo \"✗ \$name NOT found\\n\";
    }
}
"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: $PROJECT_DIR"
echo ""
echo "Files to create:"
echo "  - includes/Integrations/GreenshiftSync.php"
echo "  - includes/Controllers/FieldShortcodes.php"
echo ""
echo "Files to modify:"
echo "  - plugin.php"
echo ""
echo "Reference patterns:"
echo "  - includes/Integrations/FluentCRMSync.php"
echo "  - includes/Controllers/Shortcodes.php"
echo "  - includes/Models/Profile.php"
echo ""
echo "Commands:"
echo "  npm run build       # Build all assets"
echo "  npm run dev:admin   # Dev server (port 5174)"
echo ""
echo "WordPress URLs:"
echo "  Admin: http://tutorlms-exploration.local/wp-admin/"
echo "  REST API: http://tutorlms-exploration.local/wp-json/frs-users/v1/"
echo ""
